package com.mall.web.admin.order.vo;

// Generated 2014-7-18 13:09:35 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Order generated by hbm2java
 */
public class AdminOrderGoodsVo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3549225880245149551L;

	private String cate_id;
	private String cate_name;

	private String goods_name;
	private BigDecimal price;
	private Integer quantity;
	
	private Integer seller_id;
	private String seller_name;
	
	private String order_sn;
	private Integer status;
	private String add_time;
	private String pay_time;
	private String ship_time;
	private String finished_time;
	private String evaluation_time;

	private String addTimeS;
	private String addTimeE;
	private String payTimeS;
	private String payTimeE;
	private String shipTimeS;
	private String shipTimeE;
	private String finishedTimeS;
	private String finishedTimeE;
	private String evaluationTimeS;
	private String evaluationTimeE;

	public String getOrder_sn() {
		return order_sn;
	}

	public void setOrder_sn(String order_sn) {
		this.order_sn = order_sn;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getAdd_time() {
		return add_time;
	}

	public void setAdd_time(String add_time) {
		this.add_time = add_time != null && add_time.length() > 10 ? add_time
				.substring(0, 10) : add_time;
	}

	public String getPay_time() {
		return pay_time;
	}

	public void setPay_time(String pay_time) {
		this.pay_time = pay_time != null && pay_time.length() > 10 ? pay_time
				.substring(0, 10) : pay_time;
	}

	public String getShip_time() {
		return ship_time;
	}

	public void setShip_time(String ship_time) {
		this.ship_time = ship_time != null && ship_time.length() > 10 ? ship_time
				.substring(0, 10) : ship_time;
	}

	public String getFinished_time() {
		return finished_time;
	}

	public void setFinished_time(String finished_time) {
		this.finished_time = finished_time != null
				&& finished_time.length() > 10 ? finished_time.substring(0, 10)
				: finished_time;
	}

	public String getEvaluation_time() {
		return evaluation_time;
	}

	public void setEvaluation_time(String evaluation_time) {
		this.evaluation_time = evaluation_time != null
				&& evaluation_time.length() > 10 ? evaluation_time.substring(0,
				10) : evaluation_time;
	}

	public String getAddTimeS() {
		return addTimeS;
	}

	public void setAddTimeS(String addTimeS) {
		this.addTimeS = addTimeS;
	}

	public String getAddTimeE() {
		return addTimeE;
	}

	public void setAddTimeE(String addTimeE) {
		this.addTimeE = addTimeE;
	}

	public String getPayTimeS() {
		return payTimeS;
	}

	public void setPayTimeS(String payTimeS) {
		this.payTimeS = payTimeS;
	}

	public String getPayTimeE() {
		return payTimeE;
	}

	public void setPayTimeE(String payTimeE) {
		this.payTimeE = payTimeE;
	}

	public String getShipTimeS() {
		return shipTimeS;
	}

	public void setShipTimeS(String shipTimeS) {
		this.shipTimeS = shipTimeS;
	}

	public String getShipTimeE() {
		return shipTimeE;
	}

	public void setShipTimeE(String shipTimeE) {
		this.shipTimeE = shipTimeE;
	}

	public String getFinishedTimeS() {
		return finishedTimeS;
	}

	public void setFinishedTimeS(String finishedTimeS) {
		this.finishedTimeS = finishedTimeS;
	}

	public String getFinishedTimeE() {
		return finishedTimeE;
	}

	public void setFinishedTimeE(String finishedTimeE) {
		this.finishedTimeE = finishedTimeE;
	}

	public String getEvaluationTimeS() {
		return evaluationTimeS;
	}

	public void setEvaluationTimeS(String evaluationTimeS) {
		this.evaluationTimeS = evaluationTimeS;
	}

	public String getEvaluationTimeE() {
		return evaluationTimeE;
	}

	public void setEvaluationTimeE(String evaluationTimeE) {
		this.evaluationTimeE = evaluationTimeE;
	}

	public String getCate_id() {
		return cate_id;
	}

	public void setCate_id(String cate_id) {
		this.cate_id = cate_id;
	}

	public String getCate_name() {
		return cate_name;
	}

	public void setCate_name(String cate_name) {
		this.cate_name = cate_name;
	}

	public String getGoods_name() {
		return goods_name;
	}

	public void setGoods_name(String goods_name) {
		this.goods_name = goods_name;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getSeller_id() {
		return seller_id;
	}

	public void setSeller_id(Integer seller_id) {
		this.seller_id = seller_id;
	}

	public String getSeller_name() {
		return seller_name;
	}

	public void setSeller_name(String seller_name) {
		this.seller_name = seller_name;
	}

}
