package com.mall.web.mall.domain;

// Generated 2015-5-10 16:22:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.mall.common.util.BaseUtil;


/**
 * Ck360Category generated by hbm2java
 */
public class WebCategory implements java.io.Serializable {

	private String id;
	private WebCategory category;
	private String flag;
	private String internalCommand;
	private String name;
	private String nodeImage;
	private Integer orderNo;
	private String pageUrl;
	private String remark;
	private Set categories = new HashSet(0);
	private Set categories_1 = new HashSet(0);
	private Set articles = new HashSet(0);

	public WebCategory() {
	}

	public WebCategory(String id, String flag, String internalCommand,
			String name) {
		this.id = id;
		this.flag = flag;
		this.internalCommand = internalCommand;
		this.name = name;
	}

	public WebCategory(String id, WebCategory ck360Category, String flag,
			String internalCommand, String name, String nodeImage,
			Integer orderNo, String pageUrl, String remark,
			Set ck360Categories, Set ck360Categories_1, Set ck360Articles) {
		this.id = id;
		this.category = ck360Category;
		this.flag = flag;
		this.internalCommand = internalCommand;
		this.name = name;
		this.nodeImage = nodeImage;
		this.orderNo = orderNo;
		this.pageUrl = pageUrl;
		this.remark = remark;
		this.categories = ck360Categories;
		this.categories_1 = ck360Categories_1;
		this.articles = ck360Articles;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getInternalCommand() {
		return this.internalCommand;
	}

	public void setInternalCommand(String internalCommand) {
		this.internalCommand = internalCommand;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNodeImage() {
		return this.nodeImage;
	}

	public void setNodeImage(String nodeImage) {
		this.nodeImage = nodeImage;
	}

	public String getParentId() {
		if (BaseUtil.isEmpty(this.getCategory()))
			return null;
		else
			return this.getCategory().getId();
	}

	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = BaseUtil.null2zero(orderNo);
	}

	public String getPageUrl() {
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public WebCategory getCategory() {
		return category;
	}

	public void setCategory(WebCategory category) {
		this.category = category;
	}

	public Set getCategories() {
		return categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

	public Set getCategories_1() {
		return categories_1;
	}

	public void setCategories_1(Set categories_1) {
		this.categories_1 = categories_1;
	}

	public Set getArticles() {
		return articles;
	}

	public void setArticles(Set articles) {
		this.articles = articles;
	}

	
}
