package com.mall.web.mall.domain;

// Generated 2014-7-18 13:09:35 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * YzmOrder generated by hbm2java
 */
public class OrderTimeout extends GeneralOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8904897823349380966L;
	private int timeoutId;
	private Long orderId;
	private String orderSn;
	private String type;// 订单方式（0-直充；1-龙币）
	private int buyerId;
	private String buyerName;
	private Integer status;// 10已提交（货到付款） 11等待买家付款（非货到付款） 20等待卖家发货 30卖家已发货
							// 40交易成功 // 0交易取消
	private Date addTime;
	private Integer paymentId;
	private String paymentName;
	private String paymentCode;
	private String outTradeSn;
	private Date payTime;
	private BigDecimal discount;
	private BigDecimal orderAmount;
	private String serverCode;// 通知服务器编码
	private String userCode;// 通知用户编码
	private String roleCode;// 角色编码
	private String remark;// 备注

	private String timeoutType;
	private Date timeoutTime;

	public OrderTimeout() {
	}

	public static OrderTimeout order2Timeout(Order order, String timeoutType) {
		OrderTimeout timeout = new OrderTimeout();
		timeout.orderId = order.getOrderId();
		timeout.orderSn = order.getOrderSn();
		timeout.type = order.getType();
		timeout.buyerId = order.getBuyerId();
		timeout.buyerName = order.getBuyerName();
		timeout.status = order.getStatus();
		timeout.addTime = order.getAddTime();
		timeout.paymentId = order.getPaymentId();
		timeout.paymentName = order.getPaymentName();
		timeout.paymentCode = order.getPaymentCode();
		timeout.outTradeSn = order.getOutTradeSn();
		timeout.payTime = order.getPayTime();
		timeout.discount = order.getDiscount();
		timeout.orderAmount = order.getOrderAmount();

		timeout.serverCode = order.getServerCode();
		timeout.userCode = order.getUserCode();
		timeout.roleCode = order.getRoleCode();
		timeout.remark = order.getRemark();

		timeout.timeoutTime = new Date();
		timeout.timeoutType = timeoutType;
		return timeout;
	}

	public int getTimeoutId() {
		return timeoutId;
	}

	public void setTimeoutId(int timeoutId) {
		this.timeoutId = timeoutId;
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public String getOrderSn() {
		return orderSn;
	}

	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getBuyerId() {
		return buyerId;
	}

	public void setBuyerId(int buyerId) {
		this.buyerId = buyerId;
	}

	public String getBuyerName() {
		return buyerName;
	}

	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getAddTime() {
		return addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public Integer getPaymentId() {
		return paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	public String getPaymentName() {
		return paymentName;
	}

	public void setPaymentName(String paymentName) {
		this.paymentName = paymentName;
	}

	public String getPaymentCode() {
		return paymentCode;
	}

	public void setPaymentCode(String paymentCode) {
		this.paymentCode = paymentCode;
	}

	public String getOutTradeSn() {
		return outTradeSn;
	}

	public void setOutTradeSn(String outTradeSn) {
		this.outTradeSn = outTradeSn;
	}

	public Date getPayTime() {
		return payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	public BigDecimal getDiscount() {
		return discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public BigDecimal getOrderAmount() {
		return orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	public String getServerCode() {
		return serverCode;
	}

	public void setServerCode(String serverCode) {
		this.serverCode = serverCode;
	}

	public String getUserCode() {
		return userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getRoleCode() {
		return roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getTimeoutType() {
		return timeoutType;
	}

	public void setTimeoutType(String timeoutType) {
		this.timeoutType = timeoutType;
	}

	public Date getTimeoutTime() {
		return timeoutTime;
	}

	public void setTimeoutTime(Date timeoutTime) {
		this.timeoutTime = timeoutTime;
	}

}
