package com.mall.web.admin.order.vo;

// Generated 2014-7-18 13:09:35 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Order generated by hbm2java
 */
public class AdminOrderVo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3549225880245149551L;

	private Long order_id;
	private String order_sn;
	private String type;
	private String extension;
	private Integer seller_id;
	private String seller_name;
	private Integer buyer_id;
	private String buyer_name;
	private String buyer_email;
	private Integer status;

	private Integer return_status; // 新增

	private String invoice_id;
	private String invoice_name;

	private String add_time;
	private String add_date;
	private Integer payment_id;
	private String payment_name;
	private String payment_code;
	private String out_trade_sn;
	private String pay_time;
	private String pay_date;
	private String pay_message;
	private String ship_time;
	private String ship_date;
	private String invoice_no;
	private String finished_time;
	private BigDecimal goods_amount;
	private BigDecimal discount;
	private BigDecimal order_amount;
	private Integer evaluation_status;
	private String evaluation_time;
	private Integer anonymous;
	private String postscript;
	private boolean pay_alter;
	// private long payId;
	private Integer refund_status;
	private Integer refund_type;
	private String express_company;
	private Integer money_location;
	private BigDecimal refundable_amount;
	private Integer receive_type;
	private short is_appeal;

	private String record_time;// 退款申请时间
	private String goods_return_time;// 退货收货时间

	private String shipping_name;
	private String shipping_fee;
	private String consignee;
	private String phoneMob;
	private String payIdentity;
	private String payIdentity2;
	private BigDecimal payMoney;

	private BigDecimal creduce;
	private BigDecimal rreduce;
	private BigDecimal oreduce;

	private String addTimeS;
	private String addTimeE;
	private String payTimeS;
	private String payTimeE;
	private String shipTimeS;
	private String shipTimeE;
	private String finishedTimeS;
	private String finishedTimeE;
	private String evaluationTimeS;
	private String evaluationTimeE;

	
	/********************/
	//统计数据
	private BigDecimal order_count;
	//订单金额
	private BigDecimal order_sum;
	
	public Long getOrder_id() {
		return order_id;
	}

	public void setOrder_id(Long order_id) {
		this.order_id = order_id;
	}

	public String getOrder_sn() {
		return order_sn;
	}

	public void setOrder_sn(String order_sn) {
		this.order_sn = order_sn;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getExtension() {
		return extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getSeller_name() {
		return seller_name;
	}

	public void setSeller_name(String seller_name) {
		this.seller_name = seller_name;
	}

	public String getBuyer_name() {
		return buyer_name;
	}

	public void setBuyer_name(String buyer_name) {
		this.buyer_name = buyer_name;
	}

	public String getBuyer_email() {
		return buyer_email;
	}

	public void setBuyer_email(String buyer_email) {
		this.buyer_email = buyer_email;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getReturn_status() {
		return return_status;
	}

	public void setReturn_status(Integer return_status) {
		this.return_status = return_status;
	}

	public String getInvoice_id() {
		return invoice_id;
	}

	public void setInvoice_id(String invoice_id) {
		this.invoice_id = invoice_id;
	}

	public String getInvoice_name() {
		return invoice_name;
	}

	public void setInvoice_name(String invoice_name) {
		this.invoice_name = invoice_name;
	}

	public String getAdd_time() {
		return add_time;
	}

	public void setAdd_time(String add_time) {
		this.add_time = add_time != null && add_time.length() > 10 ? add_time
				.substring(0, 10) : add_time;
	}

	public String getAdd_date() {
		return add_date;
	}

	public void setAdd_date(String add_date) {
		this.add_date = add_date;
	}

	public Integer getPayment_id() {
		return payment_id;
	}

	public void setPayment_id(Integer payment_id) {
		this.payment_id = payment_id;
	}

	public String getPayment_name() {
		return payment_name;
	}

	public void setPayment_name(String payment_name) {
		this.payment_name = payment_name;
	}

	public String getPayment_code() {
		return payment_code;
	}

	public void setPayment_code(String payment_code) {
		this.payment_code = payment_code;
	}

	public String getOut_trade_sn() {
		return out_trade_sn;
	}

	public void setOut_trade_sn(String out_trade_sn) {
		this.out_trade_sn = out_trade_sn;
	}

	public String getPay_time() {
		return pay_time;
	}

	public void setPay_time(String pay_time) {
		this.pay_time = pay_time != null && pay_time.length() > 10 ? pay_time
				.substring(0, 10) : pay_time;
	}

	public String getPay_date() {
		return pay_date;
	}

	public void setPay_date(String pay_date) {
		this.pay_date = pay_date;
	}

	public String getPay_message() {
		return pay_message;
	}

	public void setPay_message(String pay_message) {
		this.pay_message = pay_message;
	}

	public String getShip_time() {
		return ship_time;
	}

	public void setShip_time(String ship_time) {
		this.ship_time = ship_time != null && ship_time.length() > 10 ? ship_time
				.substring(0, 10) : ship_time;
	}

	public String getShip_date() {
		return ship_date;
	}

	public void setShip_date(String ship_date) {
		this.ship_date = ship_date;
	}

	public String getInvoice_no() {
		return invoice_no;
	}

	public void setInvoice_no(String invoice_no) {
		this.invoice_no = invoice_no;
	}

	public String getFinished_time() {
		return finished_time;
	}

	public void setFinished_time(String finished_time) {
		this.finished_time = finished_time != null
				&& finished_time.length() > 10 ? finished_time.substring(0, 10)
				: finished_time;
	}

	public BigDecimal getGoods_amount() {
		return goods_amount;
	}

	public void setGoods_amount(BigDecimal goods_amount) {
		this.goods_amount = goods_amount;
	}

	public BigDecimal getDiscount() {
		return discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public BigDecimal getOrder_amount() {
		return order_amount;
	}

	public void setOrder_amount(BigDecimal order_amount) {
		this.order_amount = order_amount;
	}

	public Integer isEvaluation_status() {
		return evaluation_status;
	}

	public void setEvaluation_status(Integer evaluation_status) {
		this.evaluation_status = evaluation_status;
	}

	public String getEvaluation_time() {
		return evaluation_time;
	}

	public void setEvaluation_time(String evaluation_time) {
		this.evaluation_time = evaluation_time != null
				&& evaluation_time.length() > 10 ? evaluation_time.substring(0,
				10) : evaluation_time;
	}

	public Integer getAnonymous() {
		return anonymous;
	}

	public void setAnonymous(Integer anonymous) {
		this.anonymous = anonymous;
	}

	public String getPostscript() {
		return postscript;
	}

	public void setPostscript(String postscript) {
		this.postscript = postscript;
	}

	public boolean isPay_alter() {
		return pay_alter;
	}

	public void setPay_alter(boolean pay_alter) {
		this.pay_alter = pay_alter;
	}

	public Integer getRefund_status() {
		return refund_status;
	}

	public void setRefund_status(Integer refund_status) {
		this.refund_status = refund_status;
	}

	public Integer getRefund_type() {
		return refund_type;
	}

	public void setRefund_type(Integer refund_type) {
		this.refund_type = refund_type;
	}

	public String getExpress_company() {
		return express_company;
	}

	public void setExpress_company(String express_company) {
		this.express_company = express_company;
	}

	public Integer getMoney_location() {
		return money_location;
	}

	public void setMoney_location(Integer money_location) {
		this.money_location = money_location;
	}

	public BigDecimal getRefundable_amount() {
		return refundable_amount;
	}

	public void setRefundable_amount(BigDecimal refundable_amount) {
		this.refundable_amount = refundable_amount;
	}

	public Integer getReceive_type() {
		return receive_type;
	}

	public void setReceive_type(Integer receive_type) {
		this.receive_type = receive_type;
	}

	public short getIs_appeal() {
		return is_appeal;
	}

	public void setIs_appeal(short is_appeal) {
		this.is_appeal = is_appeal;
	}

	public String getRecord_time() {
		return record_time;
	}

	public void setRecord_time(String record_time) {
		this.record_time = record_time != null && record_time.length() > 10 ? record_time
				.substring(0, 10) : record_time;
	}

	public String getGoods_return_time() {
		return goods_return_time;
	}

	public void setGoods_return_time(String goods_return_time) {
		this.goods_return_time = goods_return_time != null
				&& goods_return_time.length() > 10 ? goods_return_time
				.substring(0, 10) : goods_return_time;
	}

	public String getConsignee() {
		return consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	public Integer getSeller_id() {
		return seller_id;
	}

	public void setSeller_id(Integer seller_id) {
		this.seller_id = seller_id;
	}

	public Integer getBuyer_id() {
		return buyer_id;
	}

	public void setBuyer_id(Integer buyer_id) {
		this.buyer_id = buyer_id;
	}

	public String getPhoneMob() {
		return phoneMob;
	}

	public void setPhoneMob(String phoneMob) {
		this.phoneMob = phoneMob;
	}

	public String getPayIdentity() {
		return payIdentity;
	}

	public String getPayIdentity2() {
		return payIdentity2;
	}

	public void setPayIdentity(String payIdentity) {
		this.payIdentity = payIdentity;
		if (payIdentity != null) {
			payIdentity2 = payIdentity;
			if (payIdentity2.indexOf("up") == 0) {
				payIdentity2 = "银联";
			} else if (payIdentity2.indexOf("ali") == 0) {
				payIdentity2 = "支付宝";
			} else if (payIdentity2.indexOf("20") == 0) {
				payIdentity2 = "微信";
			}
		} else {
			payIdentity2 = "";
		}
	}

	public BigDecimal getPayMoney() {
		return payMoney;
	}

	public void setPayMoney(BigDecimal payMoney) {
		this.payMoney = payMoney;
	}

	public BigDecimal getCreduce() {
		return creduce;
	}

	public void setCreduce(BigDecimal creduce) {
		this.creduce = creduce;
	}

	public BigDecimal getRreduce() {
		return rreduce;
	}

	public void setRreduce(BigDecimal rreduce) {
		this.rreduce = rreduce;
	}

	public BigDecimal getOreduce() {
		return oreduce;
	}

	public void setOreduce(BigDecimal oreduce) {
		this.oreduce = oreduce;
	}

	public String getAddTimeS() {
		return addTimeS;
	}

	public void setAddTimeS(String addTimeS) {
		this.addTimeS = addTimeS;
	}

	public String getAddTimeE() {
		return addTimeE;
	}

	public void setAddTimeE(String addTimeE) {
		this.addTimeE = addTimeE;
	}

	public String getPayTimeS() {
		return payTimeS;
	}

	public void setPayTimeS(String payTimeS) {
		this.payTimeS = payTimeS;
	}

	public String getPayTimeE() {
		return payTimeE;
	}

	public void setPayTimeE(String payTimeE) {
		this.payTimeE = payTimeE;
	}

	public String getShipTimeS() {
		return shipTimeS;
	}

	public void setShipTimeS(String shipTimeS) {
		this.shipTimeS = shipTimeS;
	}

	public String getShipTimeE() {
		return shipTimeE;
	}

	public void setShipTimeE(String shipTimeE) {
		this.shipTimeE = shipTimeE;
	}

	public String getFinishedTimeS() {
		return finishedTimeS;
	}

	public void setFinishedTimeS(String finishedTimeS) {
		this.finishedTimeS = finishedTimeS;
	}

	public String getFinishedTimeE() {
		return finishedTimeE;
	}

	public void setFinishedTimeE(String finishedTimeE) {
		this.finishedTimeE = finishedTimeE;
	}

	public String getEvaluationTimeS() {
		return evaluationTimeS;
	}

	public void setEvaluationTimeS(String evaluationTimeS) {
		this.evaluationTimeS = evaluationTimeS;
	}

	public String getEvaluationTimeE() {
		return evaluationTimeE;
	}

	public void setEvaluationTimeE(String evaluationTimeE) {
		this.evaluationTimeE = evaluationTimeE;
	}

	public void setPayIdentity2(String payIdentity2) {
		this.payIdentity2 = payIdentity2;
	}

	public BigDecimal getOrder_count() {
		return order_count;
	}

	public void setOrder_count(BigDecimal order_count) {
		this.order_count = order_count;
	}

	public BigDecimal getOrder_sum() {
		return order_sum;
	}

	public void setOrder_sum(BigDecimal order_sum) {
		this.order_sum = order_sum;
	}

	public String getShipping_name() {
		return shipping_name;
	}

	public void setShipping_name(String shipping_name) {
		this.shipping_name = shipping_name;
	}

	public String getShipping_fee() {
		return shipping_fee;
	}

	public void setShipping_fee(String shipping_fee) {
		this.shipping_fee = shipping_fee;
	}

}
