package com.mall.web.admin.primary.vo;

// Generated 2014-7-18 13:09:35 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * PayPrimary generated by hbm2java
 */
public class PayPrimaryVo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6217780155608579036L;

	private String primaryId;
	private String identityId;
	private String businessType;
	private BigDecimal money;
	private String serviceResponseStatus;
	private Integer status;// 1、支付中，2、支付成功
	private String requestTimeS;
	private String requestTimeE;

	private BigDecimal money4ali;// 支付宝
	private BigDecimal money4up;// 银联
	private BigDecimal money4wx;// 微信

	public PayPrimaryVo() {
	}

	public String getPrimaryId() {
		return this.primaryId;
	}

	public void setPrimaryId(String primaryId) {
		this.primaryId = primaryId;
	}

	public String getIdentityId() {
		return this.identityId;
	}

	public void setIdentityId(String identityId) {
		this.identityId = identityId;
	}

	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public String getServiceResponseStatus() {
		return this.serviceResponseStatus;
	}

	public void setServiceResponseStatus(String serviceResponseStatus) {
		this.serviceResponseStatus = serviceResponseStatus;
	}

	public BigDecimal getMoney4ali() {
		return money4ali;
	}

	public void setMoney4ali(BigDecimal money4ali) {
		this.money4ali = money4ali;
	}

	public BigDecimal getMoney4up() {
		return money4up;
	}

	public void setMoney4up(BigDecimal money4up) {
		this.money4up = money4up;
	}

	public BigDecimal getMoney4wx() {
		return money4wx;
	}

	public void setMoney4wx(BigDecimal money4wx) {
		this.money4wx = money4wx;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getRequestTimeS() {
		return requestTimeS;
	}

	public void setRequestTimeS(String requestTimeS) {
		this.requestTimeS = requestTimeS;
	}

	public String getRequestTimeE() {
		return requestTimeE;
	}

	public void setRequestTimeE(String requestTimeE) {
		this.requestTimeE = requestTimeE;
	}

}
