package com.mall.web.pay.domain;

// Generated 2014-7-18 13:09:35 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * YzmPayInteraction generated by hbm2java
 */
@Entity
@Table(name = "ml_pay_interaction")
public class PayInteraction implements java.io.Serializable {
	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "union_id", length = 32)
	private String unionId;
	
	@Column(name = "type_id")
	private long typeId;
	
	@Column(name = "order_id")
	private String orderId;
	
	@Column(name = "money")
	private BigDecimal money;
	
	@Column(name = "return_order_id")
	private String returnOrderId;
	
	@Column(name = "return_money")
	private BigDecimal returnMoney;
	
	@Column(name = "return_time")
	private Date returnTime;
	
	@Column(name = "status")
	private int status;// 1、请求数据，2、响应数据
	
	@Column(name = "create_time")
	private Date createTime;
	
	@Column(name = "reactionData")
	private String reactionData;

	public PayInteraction() {
	}

	public PayInteraction(long typeId, String orderId, BigDecimal money,
			String returnOrderId, BigDecimal returnMoney, Date returnTime,
			int status, Date createTime) {
		this.typeId = typeId;
		this.orderId = orderId;
		this.money = money;
		this.returnOrderId = returnOrderId;
		this.returnMoney = returnMoney;
		this.returnTime = returnTime;
		this.status = status;
		this.createTime = createTime;
	}

	public String getUnionId() {
		return this.unionId;
	}

	public void setUnionId(String unionId) {
		this.unionId = unionId;
	}

	public long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(long typeId) {
		this.typeId = typeId;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public String getReturnOrderId() {
		return this.returnOrderId;
	}

	public void setReturnOrderId(String returnOrderId) {
		this.returnOrderId = returnOrderId;
	}

	public BigDecimal getReturnMoney() {
		return this.returnMoney;
	}

	public void setReturnMoney(BigDecimal returnMoney) {
		this.returnMoney = returnMoney;
	}

	public Date getReturnTime() {
		return this.returnTime;
	}

	public void setReturnTime(Date returnTime) {
		this.returnTime = returnTime;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getReactionData() {
		return reactionData;
	}

	public void setReactionData(String reactionData) {
		this.reactionData = reactionData;
	}

}
