package com.mall.web.mall.domain;

// Generated 2015-5-10 16:22:00 by Hibernate Tools 4.0.0

import java.util.Date;

import com.mall.common.util.BaseUtil;

/**
 * Ck360Article generated by hbm2java
 */
public class WebArticle implements java.io.Serializable {

	private String id;
	private WebCategory category;
	private String artAbstract;
	private String content;
	private Date publishTime;
	private Integer readCount;
	private Integer supportCount;
	private String title;
	private Integer unSupportCount;
	private String publishAuthorId;
	private String publishOrgId;
	private String imgUrl;
	// 标签
	private String tag;

	public WebArticle() {
	}

	public WebArticle(String id) {
		this.id = id;
	}

	public WebArticle(String id, WebCategory ck360Category,
			String artAbstract, String content, Date publishTime,
			Integer readCount, Integer supportCount, String title,
			Integer unSupportCount, String publishAuthorId, String imgUrl) {
		this.id = id;
		this.category = ck360Category;
		this.artAbstract = artAbstract;
		this.content = content;
		this.publishTime = publishTime;
		this.readCount = readCount;
		this.supportCount = supportCount;
		this.title = title;
		this.unSupportCount = unSupportCount;
		this.publishAuthorId = publishAuthorId;
		this.imgUrl = imgUrl;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public WebCategory getCategory() {
		return this.category;
	}

	public void setCategory(WebCategory ck360Category) {
		this.category = ck360Category;
	}

	public String getArtAbstract() {
		return this.artAbstract;
	}

	public void setArtAbstract(String artAbstract) {
		this.artAbstract = artAbstract;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public Integer getReadCount() {
		return this.readCount;
	}

	public void setReadCount(Integer readCount) {
		this.readCount = BaseUtil.null2zero(readCount);
	}

	public Integer getSupportCount() {
		return this.supportCount;
	}

	public void setSupportCount(Integer supportCount) {
		this.supportCount = BaseUtil.null2zero(supportCount);
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getUnSupportCount() {
		return this.unSupportCount;
	}

	public void setUnSupportCount(Integer unSupportCount) {
		this.unSupportCount = BaseUtil.null2zero(unSupportCount);
	}

	public String getPublishAuthorId() {
		return this.publishAuthorId;
	}

	public void setPublishAuthorId(String publishAuthorId) {
		this.publishAuthorId = publishAuthorId;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getPublishOrgId() {
		return publishOrgId;
	}

	public void setPublishOrgId(String publishOrgId) {
		this.publishOrgId = publishOrgId;
	}

}
