package com.mall.web.pay.domain;

// Generated 2014-7-18 13:09:35 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * YzmPayPrimary generated by hbm2java
 */
@Entity
@Table(name = "ml_pay_primary")
public class PayPrimary implements java.io.Serializable {
	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "primary_id",length = 32)
	private String primaryId;
	
	@Column(name = "identity_id")
	private String identityId;
	
	@Column(name = "type_id")
	private long typeId;
	
	@Column(name = "user_id")
	private long userId;
	
	@Column(name = "business_type")
	private String businessType;
	
	@Column(name = "money")
	private BigDecimal money;
	
	@Column(name = "service_response_status")
	private String serviceResponseStatus;
	
	@Column(name = "status")
	private int status;//1、支付中，2、支付成功
	
	@Column(name = "request_time")
	private Date requestTime;
	
	@Column(name = "response_time")
	private Date responseTime;
	
	@Column(name = "handle_time")
	private Date handleTime;
	
	@Column(name = "thrid_order_sn")
	private String thridOrderSn;
	
	@Column(name = "balance")
	private BigDecimal balance;

	public PayPrimary() {
	}

	public PayPrimary(long typeId, long userId, String businessType,
			BigDecimal money, int status, Date requestTime) {
		this.typeId = typeId;
		this.userId = userId;
		this.businessType = businessType;
		this.money = money;
		this.status = status;
		this.requestTime = requestTime;
	}

	public PayPrimary(String identityId, long typeId, long userId,
			String businessType, BigDecimal money,
			String serviceResponseStatus, int status, Date requestTime,
			Date responseTime, Date handleTime, String thridOrderSn) {
		this.identityId = identityId;
		this.typeId = typeId;
		this.userId = userId;
		this.businessType = businessType;
		this.money = money;
		this.serviceResponseStatus = serviceResponseStatus;
		this.status = status;
		this.requestTime = requestTime;
		this.responseTime = responseTime;
		this.handleTime = handleTime;
		this.thridOrderSn = thridOrderSn;
	}

	public String getPrimaryId() {
		return this.primaryId;
	}

	public void setPrimaryId(String primaryId) {
		this.primaryId = primaryId;
	}

	public String getIdentityId() {
		return this.identityId;
	}

	public void setIdentityId(String identityId) {
		this.identityId = identityId;
	}

	public long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(long typeId) {
		this.typeId = typeId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public String getServiceResponseStatus() {
		return this.serviceResponseStatus;
	}

	public void setServiceResponseStatus(String serviceResponseStatus) {
		this.serviceResponseStatus = serviceResponseStatus;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	public Date getResponseTime() {
		return this.responseTime;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	public Date getHandleTime() {
		return this.handleTime;
	}

	public void setHandleTime(Date handleTime) {
		this.handleTime = handleTime;
	}

	public String getThridOrderSn() {
		return this.thridOrderSn;
	}

	public void setThridOrderSn(String thridOrderSn) {
		this.thridOrderSn = thridOrderSn;
	}

	public BigDecimal getBalance() {
		return balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
