package com.mall.web.mall.domain;

import java.util.Date;

// Generated 2014-7-18 13:09:35 by Hibernate Tools 3.4.0.CR1

/**
 * YzmOrder generated by hbm2java
 */
public class OrderSucc implements java.io.Serializable {

	private int orderId;
	private String type;
	private int buyerId;
	private String buyerName;
	private Integer status;
	private Date addTime;

	public OrderSucc() {
	}

	public int getOrderId() {
		return orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getBuyerId() {
		return buyerId;
	}

	public void setBuyerId(int buyerId) {
		this.buyerId = buyerId;
	}

	public String getBuyerName() {
		return buyerName;
	}

	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getAddTime() {
		return addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

}
